"""empty message

Revision ID: e7cae71599c1
Revises: d4238c6842d8
Create Date: 2026-10-08 22:18:02.064057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7cae71599c1'
down_revision: Union[str, Sequence[str], None] = 'd4238c6842d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')

    op.create_table('document',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('created_time', sa.DateTime(), nullable=True),
                    sa.Column('rubrics', sa.ARRAY(sa.String()), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('rubrics', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_pkey'))
    )
    # ### end Alembic commands ###
